export const carItems = [
    {
      id: 1,
      title: "Ciężarówka",
      brand: "Man",
      year: "2004",
      mileage: "340 000 km",
      engine: "100KM ",
      price: "35 000",
      img: "img/auto1.jpg",
      description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
    },
  
    {
      id: 2,
      title: "Audi A3",
      brand: "Audi",
      year: "2017",
      mileage: "200 000 km",
      engine: "170KM ",
      price: "18 000",
      img: "img/auto2.jpg",
      description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
    },
  
    {
      id: 3,
      title: "Audi A4",
      brand: "Audi",
      year: "2009",
      mileage: "140 000 km",
      engine: "210KM ",
      price: "26 000",
      img: "img/auto3.jpg",
      description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
    },
  
    {
      id: 4,
      title: "Audi Q5",
      brand: "Audi",
      year: "2011",
      mileage: "180 000 km",
      engine: "170KM ",
      price: "40 000",
      img: "img/auto4.jpg",
      description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
    },
  
    {
      id: 5,
      title: "Audi A6",
      brand: "Audi",
      year: "2020",
      mileage: "10 000 km",
      engine: "140KM ",
      price: "50 000",
      img: "img/auto5.jpg",
      description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
    },
  
    {
      id: 6,
      title: "Skoda combi",
      brand: "Man",
      year: "2001",
      mileage: "300 000 km",
      engine: "200KM ",
      price: "20 000",
      img: "img/auto6.jpg",
      description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
    },
  ];